export const GET_ALL_MASCOTAS = "GET_ALL_MASCOTAS";
export const GET_DETAIL_MASCOTAS = "GET_DETAIL_MASOTAS";
export const GET_FILTER_MASCOTA_BY_FUNDACION =
  "GET_FILTER_MASCOTA_BY_FUNDACION";
export const SORT_MASCOTAS_AZ = "SORT_MASCOTAS_AZ";
export const SORT_MASCOTAS_ZA = "SORT_MASCOTAS_ZA";
export const GET_ALL_FUNDACIONES = "GET_ALL_FUNDACIONES";
export const GET_DETAIL_FUNDACION = "GET_DETAIL_FUNDACION";
export const FILTER_FUNDACIONES_CIUDAD = "FILTER_FUNDACIONES_CIUDAD";
export const FILTER_FUNDACIONES_NOMBRE = "FILTER_FUNDACIONES_NOMBRE";
export const SORT_FUNDACIONES_AZ = "SORT_FUNDACIONES_AZ";
export const SORT_FUNDACIONES_ZA = "SORT_FUNDACIONES_ZA";
export const RESET_DETAIL = "RESET_DETAIL";
