export const GET_ALL_MASCOTAS = "GET_ALL_MASCOTAS";
export const GET_DETAIL_MASCOTAS = "GET_DETAIL_MASOTAS";
export const GET_ALL_FUNDACIONES = "GET_ALL_FUNDACIONES";
export const GET_DETAIL_FUNDACION = "GET_DETAIL_FUNDACION";
export const GET_ORDER_AZ = "GET_ORDER_AZ";
export const GET_ORDER_ZA = "GET_ORDER_ZA";
export const RESET_DETAIL = "RESET_DETAIL";
