export const GET_ALL_MASCOTAS = "GET_ALL_MASCOTAS";
export const GET_DETAIL_MASCOTAS = "GET_DETAIL_MASOTAS";
export const GET_ALL_FUNDACIONES = "GET_ALL_FUNDACIONES";
export const GET_DETAIL_FUNDACION = "GET_DETAIL_FUNDACION";
export const GET_FILTER_MASCOTA_BY_FUNDACION = "GET_FILTER_MASCOTA_BY_FUNDACION";
export const GET_ALL_USUARIOS = "GET_ALL_USUARIOS";
export const GET_DETALLE_USUARIO = "GET_DETALLE_USUARIO";
export const GET_FILTER_FUNDACTION_BY_CIUDAD = "GET_FILTER_FUNDACTION_BY_CIUDAD";
export const GET_NAME_FUNDACIONES = "GET_NAME_FUNDACIONES";
export const GET_REVIEWS = "GET_REVIEWS";

export const POST_MASCOTA = "POST_MASCOTA";
export const POST_ADOPCIONES = "POST_ADOPCIONES";
export const POST_FUNDACIONES = "POST_FUNDACIONES";
export const POST_DONACIONES = "POST_DONACIONES";
export const POST_USUARIO = "POST_USUARIO";
export const POST_LOGIN = "POST_LOGIN";
export const POST_REVIEWS = "POST_REVIEWS"; 

export const SORT_FUNDACIONES_AZ = "SORT_FUNDACIONES_AZ";
export const SORT_FUNDACIONES_ZA = "SORT_FUNDACIONES_ZA";
export const SORT_MASCOTAS_AZ = "SORT_MASCOTAS_AZ";
export const SORT_MASCOTAS_ZA = "SORT_MASCOTAS_ZA";


export const FILTER_FUNDACIONES_CIUDAD = "FILTER_FUNDACIONES_CIUDAD";
export const FILTER_FUNDACIONES_NOMBRE = "FILTER_FUNDACIONES_NOMBRE";
export const FILTER_MASCOTA_BY_GENERO = "FILTER_MASCOTA_BY_GENERO";
export const FILTER_MASCOTA_BY_ESPECIE = "FILTER_MASCOTA_BY_ESPECIE";

export const DELETE_MASCOTA = "DELETE_MASCOTA";
export const DELETE_USUARIO = "DELETE_USUARIO";

export const UPDATE_FUNDACION = "UPDATE_FUNDACION";
export const UPDATE_MASCOTA = "UPDATE_MASCOTA";
export const UPDATE_USUARIOS = "UPDATE_USUARIOS";

export const RESET_DETAIL = "RESET_DETAIL";
